server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.grigoryev: DEBUG

spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongo2
      port: 27017
      database: engine
      username: root
      password: password
      authentication-database: admin

