server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.grigoryev: DEBUG

spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongo1
      port: 27017
      database: car
      username: root
      password: password
      authentication-database: admin

#spring:
#  config:
#    activate:
#      on-profile: default
#
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: car
#      username: root
#      password: password
#      authentication-database: admin
#
#---
#spring:
#  config:
#    activate:
#      on-profile: integration
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: car
#      username: root
#      password: password
#      authentication-database: admin
#---
