server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.grigoryev: DEBUG

data:
  mongodb:
    port: 0
    database: car

mongodb:
  embedded:
    version: 4.8.21

---
spring:
  config:
    activate:
      on-profile: integration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: car
      username: root
      password: password
      authentication-database: admin

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongo1
      port: 27017
      database: car
      username: root
      password: password
      authentication-database: admin
